name: prueba_bbdd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
    #Para poder utilizar el supabase, copiar esto y activar el modo desarrolador con --> start ms-settings:developers
  supabase_flutter: ^2.8.3
  uuid: ^3.0.7 #para generar un id unico

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
